server:
  port: 8088
  tomcat:
    uri-encoding: UTF-8

spring:
  datasource:
    url: jdbc:mysql://rm-m5e0503y2wul76t36to.mysql.rds.aliyuncs.com:3306/project_monitor?useUnicode=true&characterEncoding=utf8&serverTimezone=GMT&useSSL=false
    username: monitor
    password: Liuyiqiangniubi666
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
    generate-ddl: true
    show-sql: true

